### ISSUE TITLE
Folder Structure/Each Patterns approach and design

### ISSUE THREAD

**Issue by jason-storey** [Naphier/unity-design-patterns#10]
Right, 

The Issue I mentioned before is that I think the concepts you have at present outlines the patterns as you understand them now, not in a way that facilitates someone who doesn't have the level of knowledge you do. 

people have a problem grasping design patterns  because of:
- Don't see the benefit
- Don't get the logic/class interaction
- Don't understand the language syntax
- Understand it in the given example but not how/when to use it in their own projects

---

so in the interest of hitting all of those pain points the trick is to walk them through it.
so i propose a folder structure under each pattern as:
-  Command Pattern
  -  What is it (only uses console write, no logic outside of pattern architecture)
    -  Without Pattern
      -  (pre pattern scripts and 1. PrePatternExample scene)
    - With Pattern
      -  (post pattern scripts and 1. PostPatternExample scene)
  -  Practical Example (actual more 'designed' code that does a thing, e.g character movement)
    -  Starting Code 
      -  Without (moves the character around using standard code)
      -  With (splits movement up into commands)
    -  New Feature/Code Change (introduces a 'problem' a scaling issue, showing how the pattern makes the solution easier)
      -  Without (changes or rewrites the code a large amount to facilitate feature)
      -  With (adds a new command, changes it with one line)
    -  Outcome (expanded examples with some exaggerated growth to show the 'without' code spagetti-ing)
      -  Without
      -  With

This stucture shows the equivalent of 
'hello world' for each pattern, 
shows the native unity alternative to make it easier to see that you are doing, 
shows a functional feature sans-pattern to give them some grounding and a relatable setting, 
'updates' the code to show what refactoring-to-patterns looks like. 
then, as they are now no doubt asking themselves, 'great i now know HOW to apply it but not WHY',
you propose a problem and show how the pattern made it easier. 

finally you give them a 'continue on from here' in both styles so they can follow along trying it both ways and getting a feel for why the pattern is an improvement.

**Comment by Naphier** [comment]
Sounds good. Please grab one of the patterns yet to be done and flesh this out. It'll be a lot more work than I originally intended (show pattern structure - show example usage), but ultimately much more helpful.
