### ISSUE TITLE
Worth bearing in mind: "Design patterns as a sign of missing language features"

### ISSUE THREAD

**Issue by andybak** [Naphier/unity-design-patterns#20]
http://wiki.c2.com/?AreDesignPatternsMissingLanguageFeatures

C# is a fairly dynamic language - as far as static languages go... I just wanted to put it out there that some of the Gang of Four patterns might map directly on to language features.

I haven't looked through this repo yet and I'm far from being either a C# expert or a Design Pattern expert but I thought it might be an interesting idea to throw into the mix.

**Comment by Naphier** [comment]
That's true. Same thing goes with Unity. Some of the design patterns just aren't useful there (or at least I can't figure out where they'd be used). For example, flyweight.
